# 1. Identit√© du ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k-guard-sa
  namespace: k-guard

---
# 2. On passe en ClusterRole pour voir tous les namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k-guard-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces", "nodes"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]

---
# 3. On lie au niveau du cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k-guard-cluster-rb
subjects:
  - kind: ServiceAccount
    name: k-guard-sa
    namespace: k-guard
roleRef:
  kind: ClusterRole
  name: k-guard-cluster-role
  apiGroup: rbac.authorization.k8s.io