apiVersion: v1
kind: Service
metadata:
  name: k-guard-service
spec:
  selector:
    app: k-guard
  ports:
    - name: front
      port: 80
      targetPort: 5173
    - name: back
      port: 8000
      targetPort: 8000